name: forecast
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  provider: ^6.0.0
  weather: ^3.1.1
  intl: ^0.19.0
  geocoding: ^2.0.1
  geolocator: ^9.0.1
  weather_animation: ^1.1.1
  shared_preferences: ^2.0.15
  connectivity_plus: ^3.0.3
  flutter_launcher_icons: ^0.13.1

  lottie: ^2.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/appicon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/appicon.png"

flutter:


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/lottie/



